# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracetest < Formula
  desc ""
  homepage "https://tracetest.kubeshop.io/"
  version "0.6.4"
  license "MIT"

  on_macos do
    url "https://github.com/schoren/tracetest/releases/download/v0.6.4/tracetest_0.6.4_darwin_all.tar.gz"
    sha256 "f085d57470bf767c87e4905f9c485135ded75e8319115522a7564769673b2bc9"

    def install
      bin.install "tracetest"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoren/tracetest/releases/download/v0.6.4/tracetest_0.6.4_linux_arm64.tar.gz"
      sha256 "e50a3168a6b1ecfa87687f535f61f75c78540c7eca22e730cfc6dcb18e8023ed"

      def install
        bin.install "tracetest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/schoren/tracetest/releases/download/v0.6.4/tracetest_0.6.4_linux_amd64.tar.gz"
      sha256 "d3609f7ecc2d3a0722af1781cdad53d6ef5ab3485ba6193ffd2a8b7775151a52"

      def install
        bin.install "tracetest"
      end
    end
  end
end
