# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tracetest < Formula
  desc ""
  homepage "https://tracetest.kubeshop.io/"
  version "0.11.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/tracetest/releases/download/v0.11.16/tracetest_0.11.16_darwin_amd64.tar.gz"
      sha256 "bbe534782536af73da0c5316ab6f189b85fda81ae594ca727256d1ac2da35761"

      def install
        bin.install "tracetest"
        bin.install "tracetest-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/tracetest/releases/download/v0.11.16/tracetest_0.11.16_darwin_arm64.tar.gz"
      sha256 "7ec7a7b46d40224561469b9bc079cb1eeed9429dbb676c632f23a866e9953237"

      def install
        bin.install "tracetest"
        bin.install "tracetest-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/tracetest/releases/download/v0.11.16/tracetest_0.11.16_linux_amd64.tar.gz"
      sha256 "47749f1a49e03c8eb985a05aa604a3c1e20a0f9f31a271a0f5891ccfd01bac27"

      def install
        bin.install "tracetest"
        bin.install "tracetest-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/tracetest/releases/download/v0.11.16/tracetest_0.11.16_linux_arm64.tar.gz"
      sha256 "ab2d3891f0d538ea50de57c9a413f3394ffa3b9c9c96dffad103759b849bb620"

      def install
        bin.install "tracetest"
        bin.install "tracetest-server"
      end
    end
  end
end
